### ISSUE TITLE
Compiling error with the test suite

### ISSUE THREAD

**Issue by imalipusram** [Billwilliams1952/AD9833-Library-Arduino#3]
Hi Bill, 

I'm trying to compile the test suite in the Arduino 1.8.1 IDE, but I get an error: 

AD9833_test_suite.ino:

 In function 'void setup()':
AD9833_test_suite:66: error: 'CLOCK_OUTPUT' was not declared in this scope
     pinMode(CLOCK_OUTPUT,OUTPUT);
             ^
exit status 1
'CLOCK_OUTPUT' was not declared in this scope

Supposedly CLOCK_OUTPUT may be defined as the pin used for SCLK in SPI. 

Any clues what could have gone wrong?
Thanks for any suggestions!

(I thought I'd better ask before I start messing up the code. At least, when I insert a declaration of CLOCK_OUTPUT, the error is gone.
Also renaming CLOCK_OUTPUT with SCK removes the compile error).

**Comment by Billwilliams1952** [comment]
Sorry about that!

Let me take a look and I'll get back to you. 

Bill

**Comment by Billwilliams1952** [comment]
Mu bad.  Somehow two lines using CLOCK_PIN were added to the file. (So much for my proper use of version control.)  Just delete the two lines.  I updated the file in the repository.

Bill
